// bun_svelte/frontend/src/components/ui/Input.svelte
<script lang="ts">
  import { Eye, EyeOff } from 'lucide-svelte';

  interface Props {
    label?: string;
    type?: string;
    value?: string;
    placeholder?: string;
    required?: boolean;
    disabled?: boolean;
    error?: string | null;
    helperText?: string;
    leftIcon?: any;
    class?: string;
    name?: string;
    id?: string;
    autocomplete?: string;
  }

  let {
    label = '',
    type = 'text',
    value = $bindable(''),
    placeholder = '',
    required = false,
    disabled = false,
    error = null,
    helperText = '',
    leftIcon: LeftIcon,
    class: className = '',
    name = '',
    id = '',
    autocomplete = 'off',
  }: Props = $props();

  const inputId = $derived(id || (name ? `input-${name}` : (label ? `input-${label.toLowerCase().replace(/[^a-z0-9]/g, '-')}` : undefined)));
  let showPassword = $state(false);
  let isPassword = $derived(type === 'password');
  let currentType = $derived(isPassword ? (showPassword ? 'text' : 'password') : type);
</script>

<div class="space-y-1.5 w-full {className}">
  {#if label}
    <label for={inputId} class="block text-xs font-semibold text-[#18181B]">
      {label}
      {#if required}
        <span class="text-[#FF634A]">*</span>
      {/if}
    </label>
  {/if}

  <div class="relative flex items-center">
    {#if LeftIcon}
      <div class="absolute left-3 text-[#8E8E93] pointer-events-none flex items-center justify-center">
        <LeftIcon class="w-4 h-4" />
      </div>
    {/if}

    <input
      id={inputId}
      type={currentType}
      bind:value={value}
      {placeholder}
      {disabled}
      {required}
      {name}
      autocomplete={autocomplete as any}
      class="w-full bg-white text-[#18181B] text-xs sm:text-sm rounded-xl border transition-colors duration-150 py-2.5 
      {LeftIcon ? 'pl-9' : 'pl-3.5'} 
      {isPassword ? 'pr-10' : 'pr-3.5'}
      {error ? 'border-[#EF4444] focus:ring-1 focus:ring-[#EF4444] focus:border-[#EF4444]' : 'border-[#D2D2D4] focus:border-[#FF634A] focus:ring-1 focus:ring-[#FF634A]'}
      focus:outline-none placeholder:text-[#8E8E93] disabled:bg-[#F4F4F6] disabled:text-[#8E8E93]"
    />

    {#if isPassword}
      <button
        type="button"
        onclick={() => showPassword = !showPassword}
        class="absolute right-3 text-[#8E8E93] hover:text-[#18181B] transition-colors p-0.5 cursor-pointer"
        tabindex="-1"
      >
        {#if showPassword}
          <EyeOff class="w-4 h-4" />
        {:else}
          <Eye class="w-4 h-4" />
        {/if}
      </button>
    {/if}
  </div>

  {#if error}
    <p class="text-[11px] font-medium text-[#EF4444]">{error}</p>
  {:else if helperText}
    <p class="text-[11px] text-[#8E8E93]">{helperText}</p>
  {/if}
</div>

// mova_app/single-tenant/frontend/src/components/ui/Input.jsx
import React, { forwardRef } from "react";
import { AlertCircle } from "lucide-react";
import { cn } from "./Button.jsx";

/**
 * Carbon Text Input Component
 * Follows Carbon form field specifications:
 * - Label: label-01
 * - Field: bg(--cds-field), bottom border 1px solid (--cds-border-strong)
 * - Height: 32px (sm), 40px (md), 48px (lg)
 * - Error: border 2px solid (--cds-support-error) with error message
 */
export const Input = forwardRef(function Input(
  {
    className = "",
    type = "text",
    id,
    label,
    error,
    helperText,
    icon: Icon,
    rightElement,
    size = "md", // sm (32px) | md (40px) | lg (48px)
    disabled = false,
    ...props
  },
  ref
) {
  const sizeStyles = {
    sm: "h-[32px] text-[12px] px-[12px]",
    md: "h-[40px] text-[14px] px-[16px]",
    lg: "h-[48px] text-[14px] px-[16px]",
  };

  return (
    <div className="w-full flex flex-col gap-[var(--cds-spacing-02)]">
      {label && (
        <label
          htmlFor={id}
          className="cds-label-01 text-[var(--cds-text-secondary)] select-none flex items-center justify-between"
        >
          <span>{label}</span>
        </label>
      )}

      <div className="relative flex items-center w-full">
        {Icon && (
          <div className="absolute left-[12px] flex items-center pointer-events-none text-[var(--cds-icon-secondary)]">
            <Icon className="w-4 h-4" />
          </div>
        )}

        <input
          ref={ref}
          id={id}
          type={type}
          disabled={disabled}
          className={cn(
            "w-full bg-[var(--cds-field)] hover:bg-[var(--cds-field-hover)] text-[var(--cds-text-primary)] placeholder:text-[var(--cds-text-placeholder)] border-b border-[var(--cds-border-strong)] transition-colors focus:outline-none focus:outline-2 focus:outline-offset-[-2px] focus:outline-[var(--cds-focus)] disabled:opacity-50 disabled:cursor-not-allowed",
            sizeStyles[size] || sizeStyles.md,
            Icon && "pl-[36px]",
            rightElement && "pr-[36px]",
            error && "border-2 border-[var(--cds-support-error)] focus:outline-[var(--cds-support-error)]",
            className
          )}
          {...props}
        />

        {rightElement && (
          <div className="absolute right-[12px] flex items-center text-[var(--cds-icon-secondary)]">
            {rightElement}
          </div>
        )}
      </div>

      {error ? (
        <div className="flex items-center gap-[var(--cds-spacing-02)] text-[var(--cds-support-error)] cds-helper-text-01 font-normal not-italic">
          <AlertCircle className="w-3.5 h-3.5 shrink-0" />
          <span>{error}</span>
        </div>
      ) : helperText ? (
        <p className="cds-helper-text-01 text-[var(--cds-text-helper)]">{helperText}</p>
      ) : null}
    </div>
  );
});
