// bun_svelte/frontend/src/components/ui/Button.svelte
<script lang="ts">
  import { Loader2 } from 'lucide-svelte';

  interface Props {
    type?: 'button' | 'submit' | 'reset';
    variant?: 'primary' | 'secondary' | 'outline' | 'danger' | 'ghost';
    size?: 'sm' | 'md' | 'lg';
    isPending?: boolean;
    loading?: boolean;
    disabled?: boolean;
    leftIcon?: any;
    rightIcon?: any;
    class?: string;
    onclick?: (e: MouseEvent) => void;
    children?: any;
  }

  let {
    type = 'button',
    variant = 'primary',
    size = 'md',
    isPending = false,
    loading = false,
    disabled = false,
    leftIcon: LeftIcon,
    rightIcon: RightIcon,
    class: className = '',
    onclick,
    children,
  }: Props = $props();

  const isSpinning = $derived(isPending || loading);

  const variantStyles = {
    primary: 'bg-[#FF634A] hover:bg-[#E54E36] active:bg-[#B82814] text-white shadow-xs border border-transparent',
    secondary: 'bg-[#E7E7E7] hover:bg-[#D2D2D4] text-[#18181B] border border-[#D2D2D4]',
    outline: 'bg-white hover:bg-[#F4F4F6] text-[#18181B] border border-[#D2D2D4]',
    danger: 'bg-[#EF4444] hover:bg-[#DC2626] text-white shadow-xs border border-transparent',
    ghost: 'bg-transparent hover:bg-[#E7E7E7] text-[#52525B]',
  };

  const sizeStyles = {
    sm: 'px-3 py-1.5 text-xs rounded-lg gap-1.5',
    md: 'px-4 py-2.5 text-sm rounded-xl gap-2',
    lg: 'px-5 py-3 text-base rounded-xl gap-2.5',
  };
</script>

<button
  {type}
  disabled={disabled || isSpinning}
  {onclick}
  class="inline-flex items-center justify-center font-bold tracking-tight transition-all duration-150 cursor-pointer disabled:opacity-60 disabled:cursor-not-allowed active:scale-[0.98] {variantStyles[variant]} {sizeStyles[size]} {className}"
>
  {#if isSpinning}
    <Loader2 class="w-4 h-4 animate-spin shrink-0" />
  {:else if LeftIcon}
    <LeftIcon class="w-4 h-4 shrink-0" />
  {/if}

  <span>
    {@render children?.()}
  </span>

  {#if !isSpinning && RightIcon}
    <RightIcon class="w-4 h-4 shrink-0" />
  {/if}
</button>

// apps/single-tenant/nodejs_react/frontend/src/components/common/Button.jsx
import React from "react";
import { cn } from "../../lib/utils.js";
import { Loader2 } from "lucide-react";

export function Button({
  children,
  variant = "primary",
  size = "md",
  className = "",
  disabled = false,
  isPending = false,
  loading = false,
  leftIcon: LeftIcon = null,
  rightIcon: RightIcon = null,
  type = "button",
  onClick,
  ...props
}) {
  const isLoading = isPending || loading;
  const isDisabled = disabled || isLoading;

  const baseStyles =
    "inline-flex items-center justify-center font-medium transition-all rounded-lg select-none " +
    "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 " +
    "disabled:opacity-50 disabled:pointer-events-none disabled:cursor-not-allowed cursor-pointer " +
    "active:scale-[0.98]";

  const variants = {
    primary:
      "bg-[#FF634A] hover:bg-[#E54E36] text-white focus-visible:ring-[#FF634A] shadow-xs font-semibold border border-transparent",
    secondary:
      "bg-slate-900 hover:bg-slate-800 text-white focus-visible:ring-slate-700 font-semibold border border-transparent",
    outline:
      "border border-[#D2D2D4] bg-white text-slate-700 hover:bg-[#E7E7E7] hover:text-slate-900 focus-visible:ring-[#D2D2D4] font-medium shadow-xs",
    ghost:
      "bg-transparent hover:bg-[#E7E7E7] text-slate-600 hover:text-slate-900 focus-visible:ring-slate-300 font-medium border border-transparent",
    danger:
      "bg-rose-600 hover:bg-rose-700 text-white focus-visible:ring-rose-500 font-semibold shadow-xs border border-transparent",
    subtle:
      "bg-[#FF634A]/10 text-[#FF634A] hover:bg-[#FF634A]/20 focus-visible:ring-[#FF634A] font-semibold border border-[#FF634A]/20",
  };

  const sizes = {
    sm: "px-3 py-1.5 text-xs gap-1.5 min-h-[36px]",
    md: "px-4 py-2.5 text-xs md:text-sm gap-2 min-h-[44px]",
    lg: "px-5 py-3 text-sm md:text-base gap-2.5 min-h-[48px]",
    icon: "w-10 h-10 p-0 min-h-[40px] min-w-[40px]",
  };

  return (
    <button
      type={type}
      disabled={isDisabled}
      onClick={onClick}
      className={cn(
        baseStyles,
        variants[variant] || variants.primary,
        sizes[size] || sizes.md,
        className
      )}
      {...props}
    >
      {isLoading && <Loader2 className="w-4 h-4 animate-spin shrink-0" />}
      {!isLoading && LeftIcon && <LeftIcon className="w-4 h-4 shrink-0" />}
      <span>{children}</span>
      {!isLoading && RightIcon && <RightIcon className="w-4 h-4 shrink-0" />}
    </button>
  );
}
