// bun_svelte/frontend/src/components/ui/Alert.svelte
<script lang="ts">
  import { 
    AlertCircle, 
    CheckCircle2, 
    AlertTriangle, 
    Info 
  } from 'lucide-svelte';

  interface Props {
    variant?: 'danger' | 'success' | 'warning' | 'info';
    title?: string;
    children?: any;
    class?: string;
  }

  let { 
    variant = 'info', 
    title = '', 
    children, 
    class: className = '' 
  }: Props = $props();

  const variantStyles = {
    danger: 'bg-[#FEF2F2] border-[#FECACA] text-[#991B1B]',
    success: 'bg-[#ECFDF5] border-[#A7F3D0] text-[#065F46]',
    warning: 'bg-[#FFFBEB] border-[#FDE68A] text-[#92400E]',
    info: 'bg-[#EFF6FF] border-[#BFDBFE] text-[#1E40AF]',
  };
</script>

<div class="p-3.5 rounded-xl border text-xs flex items-start gap-3 shadow-xs {variantStyles[variant]} {className}" role="alert">
  <div class="shrink-0 mt-0.5">
    {#if variant === 'danger'}
      <AlertCircle class="w-4 h-4" />
    {:else if variant === 'success'}
      <CheckCircle2 class="w-4 h-4" />
    {:else if variant === 'warning'}
      <AlertTriangle class="w-4 h-4" />
    {:else}
      <Info class="w-4 h-4" />
    {/if}
  </div>
  <div class="flex-1 space-y-0.5 leading-relaxed">
    {#if title}
      <h4 class="font-bold text-xs">{title}</h4>
    {/if}
    <div class="text-[11px] opacity-95">
      {@render children?.()}
    </div>
  </div>
</div>

// nodejs_react/frontend_old/src/components/ui/Alert.jsx
import React from "react";
import { cn } from "../../lib/utils.js";
import { Info, CheckCircle2, AlertTriangle, AlertCircle, X } from "lucide-react";

export function Alert({
  variant = "info",
  title,
  children,
  onClose,
  className = "",
  ...props
}) {
  const configs = {
    info: {
      bg: "bg-blue-50/90 text-blue-900 border-blue-200",
      icon: Info,
      iconColor: "text-blue-600",
    },
    success: {
      bg: "bg-emerald-50/90 text-emerald-900 border-emerald-200",
      icon: CheckCircle2,
      iconColor: "text-emerald-600",
    },
    warning: {
      bg: "bg-amber-50/90 text-amber-900 border-amber-200",
      icon: AlertTriangle,
      iconColor: "text-amber-600",
    },
    danger: {
      bg: "bg-rose-50/90 text-rose-900 border-rose-200",
      icon: AlertCircle,
      iconColor: "text-rose-600",
    },
  };

  const config = configs[variant] || configs.info;
  const Icon = config.icon;

  return (
    <div
      role="alert"
      className={cn(
        "p-3.5 md:p-4 rounded-xl border flex items-start gap-3 text-xs md:text-sm shadow-xs",
        config.bg,
        className
      )}
      {...props}
    >
      <Icon className={cn("w-5 h-5 shrink-0 mt-0.5", config.iconColor)} />
      <div className="flex-1 space-y-0.5">
        {title && <h5 className="font-heading font-bold text-xs md:text-sm leading-tight">{title}</h5>}
        <div className="font-normal leading-relaxed text-[11px] md:text-xs opacity-90">{children}</div>
      </div>
      {onClose && (
        <button
          type="button"
          onClick={onClose}
          aria-label="Tutup pemberitahuan"
          className="p-1 rounded-md opacity-70 hover:opacity-100 hover:bg-black/5 transition-opacity cursor-pointer shrink-0"
        >
          <X className="w-4 h-4" />
        </button>
      )}
    </div>
  );
}
